name: CI

on:
  push:
    branches: [main, refactor/**]
  pull_request:

jobs:
  lint-type-unit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('deploy/api/requirements.api.txt', 'deploy/worker-vision/requirements.worker.cpu.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deploy/api/requirements.api.txt \
                     -r deploy/worker-vision/requirements.worker.cpu.txt \
                     pytest ruff black mypy
      - name: Ruff
        run: ruff check .
      - name: Black
        run: black --check .
      - name: Mypy
        run: mypy deploy/api deploy/worker-vision
      - name: Pytest
        run: pytest

  build-images:
    runs-on: ubuntu-22.04
    needs: lint-type-unit
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/api/Dockerfile
          push: false
          tags: hotmama/api:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build worker CPU image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/worker-vision/Dockerfile
          target: cpu
          push: false
          tags: hotmama/worker-vision:cpu-ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

  smoke-compose-cpu:
    runs-on: ubuntu-22.04
    needs: build-images
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment
        run: cp .env.example .env
      - name: Smoke test stack (CPU)
        run: ./tools/test_compose_smoke.sh

  build-images-gpu:
    runs-on: ubuntu-22.04
    needs: build-images
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build CUDA worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/worker-vision/Dockerfile
          target: cuda
          push: false
          tags: hotmama/worker-vision:cuda-ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
